### ISSUE TITLE
Front | Docs

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/sss-computing-client#54] opened 2024-08-30 13:37 UTC
- [ ] User guide

Suggestion of the struct
```text
.
├── ...
├── doc                    # Documentation files
│   ├── algorithm              # Documantation of the algorithms 
│   │   ├── part1              # Part 1 of algorithms
│   │   │   ├── chapter1              # Chapter 1 of Part 1 of algorithms
│   │   │   │   ├── section1              # Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   ├── algorithm1              # Algorithm 1 of Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   │   ├── point1.md              # Point 1 of Algorithm 1 of Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   │   ├── point2.md              # Point 2 of Algorithm 1 of Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   │   ├── point3.md              # Point 3 of Algorithm 1 of Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   │   └── ...                 # etc.
│   │   │   │   │   ├── algorithm2              # Algorithm 2 of Section 1 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   │   └── ...                 # etc.
│   │   │   │   ├── section2              # Section 2 of Chapter 1 of Part 1 of algorithms
│   │   │   │   │   └── ...                 # etc.
│   │   │   ├── chapter2              # Chapter 2 of algorithms
│   │   │   │   └── ...                 # etc.
│   │   ├── part2              # Part 2 of algorithms
│   │   │   └── ...                 # etc.
│   │   └── ...                # etc.
│   ├── reference              # Reference Documantation 
│   └── ...                 # etc.
└── ...
```

**Comment by nyaneet** [comment] 2024-09-23 15:36
Duplicate of #60

**Closed** 2024-09-23 15:36 UTC
